- name: Ensure that group exists.
  ansible.builtin.group:
    name: "{{ frp_common['group'] }}"
    state: present

- name: Ensure that user exists.
  ansible.builtin.user:
    name: "{{ frp_common['user'] }}"
    group: "{{ frp_common['group'] }}"
    shell: /sbin/nologin
    create_home: true
    home: "{{ homedir }}"
    system: true
    state: present

- name: Ensure that folders are exists.
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ frp_common['user'] }}"
    group: "{{ frp_common['group'] }}"
    mode: '0775'
  with_items:
    - "{{ etcdir }}"
    - "{{ sbindir }}"
    - "{{ logdir }}"
    - "{{ tlsdir }}"


