---
# handlers file for ansible-role-frp

- name: Start frpc service.
  ansible.builtin.systemd:
    name: frpc.service
    enabled: true
    state: started

- name: Restart frpc service.
  ansible.builtin.systemd:
    name: frpc.service
    state: restarted

- name: Start frps service.
  ansible.builtin.systemd:
    name: frps.service
    enabled: true
    state: started

- name: Restart frps service.
  ansible.builtin.systemd:
    name: frps.service
    state: restarted
